# Generated by Django 5.0.2 on 2024-02-23 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='unique_code',
            new_name='slug',
        ),
    ]
